version: '3.3'

services:
  backend:
    image: backend
    build: backend
    env_file: .env
    volumes:
      - ./backend/code:/code

  postgres:
    image: postgres:10.1
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2.11

volumes:
  postgres-data:
