version: '3.3'

services:
  backend:
    image: backend
    build: backend
    env_file: .env
    tty: true
    volumes:
      - ./backend/code:/code
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:10.1
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.3.8-bionic
    env_file: .env
    volumes:
      - mariadb-data:/var/lib/mysql
  redis:
    image: redis:3.2.11

volumes:
  postgres-data:
  mariadb-data:
